version: 2.1
jobs:
  build:
    docker:
      - image: "debian:buster"
    branches:
      only:
        - dev-12-10-2019
        - master
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: "apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*"
      - run:
          name: Installing BUILD TOOLS
          command: "apt-get update && apt-get install -y gcc g++ cmake"
      - run:
          name: Compiling
          command: "make clean && make"
